# Generated by Django 4.1.7 on 2025-05-14 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EducationProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название программы"),
                ),
                ("link", models.URLField(verbose_name="Ссылка на сайт")),
                ("description", models.TextField(verbose_name="Описание программы")),
                (
                    "learning_outcomes",
                    models.TextField(verbose_name="Результаты обучения"),
                ),
                ("advantages", models.TextField(verbose_name="Преимущества")),
                (
                    "career_prospects",
                    models.TextField(verbose_name="Карьерные перспективы"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FellowStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "second_name",
                    models.CharField(max_length=100, verbose_name="Фамилия"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                (
                    "parent_name",
                    models.CharField(max_length=100, verbose_name="Отчество"),
                ),
                (
                    "program_name",
                    models.CharField(max_length=200, verbose_name="Название программы"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Электронная почта"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                (
                    "photo",
                    models.ImageField(upload_to="fellows", verbose_name="Фотография"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ManagementMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "second_name",
                    models.CharField(max_length=100, verbose_name="Фамилия"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                (
                    "parent_name",
                    models.CharField(max_length=100, verbose_name="Отчество"),
                ),
                (
                    "program_name",
                    models.CharField(max_length=200, verbose_name="Название программы"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            (
                                "Академический руководитель",
                                "Академический руководитель",
                            ),
                            ("Менеджер", "Менеджер программы"),
                        ],
                        max_length=30,
                        verbose_name="Роль",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Электронная почта"),
                ),
                (
                    "photo",
                    models.ImageField(upload_to="managers", verbose_name="Фотография"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "second_name",
                    models.CharField(max_length=100, verbose_name="Фамилия"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                (
                    "parent_name",
                    models.CharField(max_length=100, verbose_name="Отчество"),
                ),
                (
                    "program_name",
                    models.CharField(max_length=200, verbose_name="Название программы"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Электронная почта"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                ("resume", models.TextField(verbose_name="Резюме")),
                (
                    "photo",
                    models.ImageField(upload_to="students", verbose_name="Фотография"),
                ),
            ],
        ),
    ]
